# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release --no-restore --property:PublishDir=./publish
    # - name: Upload Windows artifacts
    #   uses: actions/upload-artifact@v3.1.3
    #   with:
    #     name: Bakabase.Tool.FixFileMoverPadding.win-x64
    #     path: publish
    # - name: release
    #   uses: actions/create-release@v1
    #   id: create_release
    #   with:
    #     draft: false
    #     prerelease: false
    #     release_name: v1.0.0
    #     tag_name: v1.0.0
    #     # tag_name: ${{ github.ref }}
    #     # body_path: CHANGELOG.md
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    - name: Gets latest created release info
      id: latest_release_info
      uses: jossef/action-latest-release-info@v1.2.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
        asset_path: ./publish/Bakabase.Tool.FixFileMoverPadding.exe
        asset_name: Bakabase.Tool.FixFileMoverPadding.win-x64.exe
        asset_content_type: application/zip
